module.exports = {

    POST_CLUB_REQUEST: "app/POST_CLUB_REQUEST",
    POST_CLUB_SUCCESS: "app/POST_CLUB_SUCCESS",
    POST_CLUB_ERROR: "app/POST_CLUB_ERROR",
    POST_CLUB_PROGRESS_SUCCESS: "app/POST_CLUB_PROGRESS_SUCCESS",
    GET_CLUB_REQUEST: "app/GET_CLUB_REQUEST",
    GET_CLUB_SUCCESS: "app/GET_CLUB_SUCCESS",
    GET_CLUB_ERROR: "app/GET_CLUB_ERROR",
    DELETE_CLUB_REQUEST: "app/DELETE_CLUB_REQUEST",
    DELETE_CLUB_SUCCESS: "app/DELETE_CLUB_SUCCESS",
    DELETE_CLUB_ERROR: "app/DELETE_CLUB_ERROR",
    UPDATE_CLUB: "app/UPDATE_UPLOAD",
}