module.exports = {
    POST_UPLOAD_REQUEST: 'app/POST_UPLOAD_REQUEST',
    POST_UPLOAD_SUCCESS: 'app/POST_UPLOAD_SUCCESS',
    POST_UPLOAD_ERROR: 'app/POST_UPLOAD_ERROR',
    POST_UPLOAD_PROGRESS_SUCCESS: 'app/POST_UPLOAD_PROGRESS_SUCCESS',
    GET_UPLOAD_REQUEST: 'app/GET_UPLOAD_REQUEST',
    GET_UPLOAD_SUCCESS: 'app/GET_UPLOAD_SUCCESS',
    GET_UPLOAD_ERROR: 'app/GET_UPLOAD_ERROR',
    DELETE_UPLOAD_REQUEST: 'app/DELETE_UPLOAD_REQUEST',
    DELETE_UPLOAD_SUCCESS: 'app/DELETE_UPLOAD_SUCCESS',
    DELETE_UPLOAD_ERROR: 'app/DELETE_UPLOAD_ERROR',
    UPDATE_UPLOAD: 'app/UPDATE_UPLOAD',
};
